# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: student.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'student.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x07student\"I\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nclass_name\x18\x03 \x01(\t\x12\x10\n\x08phone_no\x18\x04 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"1\n\x0bStudentList\x12\"\n\x08students\x18\x01 \x03(\x0b\x32\x10.student.Student\"\x17\n\tStudentID\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x65mpty2\xe3\x01\n\x0eStudentService\x12\x31\n\nAddStudent\x12\x10.student.Student\x1a\x11.student.Response\x12\x32\n\nGetStudent\x12\x0e.student.empty\x1a\x14.student.StudentList\x12\x36\n\rDeleteStudent\x12\x12.student.StudentID\x1a\x11.student.Response\x12\x32\n\x0b\x45\x64itStudent\x12\x10.student.Student\x1a\x11.student.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENT']._serialized_start=26
  _globals['_STUDENT']._serialized_end=99
  _globals['_RESPONSE']._serialized_start=101
  _globals['_RESPONSE']._serialized_end=128
  _globals['_STUDENTLIST']._serialized_start=130
  _globals['_STUDENTLIST']._serialized_end=179
  _globals['_STUDENTID']._serialized_start=181
  _globals['_STUDENTID']._serialized_end=204
  _globals['_EMPTY']._serialized_start=206
  _globals['_EMPTY']._serialized_end=213
  _globals['_STUDENTSERVICE']._serialized_start=216
  _globals['_STUDENTSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
