# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\" \n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x14\n\x06TodoId\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x08TodoList\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"\x07\n\x05\x45mpty\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb1\x01\n\x0bTodoService\x12%\n\x07\x41\x64\x64Todo\x12\n.todo.Todo\x1a\x0e.todo.Response\x12\'\n\x08ViewTodo\x12\x0b.todo.Empty\x1a\x0e.todo.TodoList\x12*\n\nDeleteTodo\x12\x0c.todo.TodoId\x1a\x0e.todo.Response\x12&\n\x08\x45\x64itTodo\x12\n.todo.Todo\x1a\x0e.todo.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=20
  _globals['_TODO']._serialized_end=52
  _globals['_TODOID']._serialized_start=54
  _globals['_TODOID']._serialized_end=74
  _globals['_TODOLIST']._serialized_start=76
  _globals['_TODOLIST']._serialized_end=113
  _globals['_EMPTY']._serialized_start=115
  _globals['_EMPTY']._serialized_end=122
  _globals['_RESPONSE']._serialized_start=124
  _globals['_RESPONSE']._serialized_end=151
  _globals['_TODOSERVICE']._serialized_start=154
  _globals['_TODOSERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
